# Site settings
title: Hyde
email: bstevensondev@gmail.com
description: A website for Hyde editor
owner:
  name: Brett Stevenson # or company name
  url: http://brettstevenson.io
repo: https://github.com/tterb/Hyde
bugs: https://github.com/tterb/Hyde/issues/new
first_published: 2017
baseurl: "/hyde/" # the subpath of your site, e.g. /blog/

url: "" # the base hostname & protocol for your site
twitter_username: bstevensondev
github_username:  tterb

name: 'Brett Stevenson'
author: 'Brett Stevenson'
favicon: images/favicon.png

# Build settings
markdown: kramdown
highlighter: rouge
sass:
 style: compressed

# Pagination
# paginate: 15
# paginate_path: "/blog/page:num/"

# html_proofer:
#   check_favicon: true
#   check_html: true
#   file_ignore:
#     - /a.*regexp*/
#     - a_string
#     - bower_components/*
#     - fonts/*
#   url_ignore:
#     - /Hyde/

exclude: ['template.md', '.gitignore', 'TODO.md', 'README.md', 'Gulpfile.js', 'package.json', 'node_modules', 'jspm_packages']
include: ['_pages','.htaccess']
defaults:
  - scope:
      path: _pages
    values:
      layout: page

plugins:
  - jekyll-paginate
